# Note: You must restart bin/webpack-dev-server for changes to take effect
# 注意: 変更を反映するためには bin/webpack-dev-server を再起動する必要があります

# 全ての環境で共通の設定
default: &default
  # JavaScriptファイルのソースコードが含まれるディレクトリのパス
  source_path: app/javascript
  # Webpackエントリーポイントのディレクトリのパス
  source_entry_path: packs
  # 公開されるファイルのルートディレクトリのパス
  public_root_path: public
  # Webpackが生成したファイルの出力先ディレクトリのパス
  public_output_path: packs
  # Webpackのキャッシュファイルの保存先ディレクトリのパス
  cache_path: tmp/cache/webpacker

  # webpackがモジュールを検索する追加のパス
  additional_paths: []

  # 全てのリクエストでmanifest.jsonを再読み込みして最新のコンパイル済みパックを再読み込みする
  cache_manifest: false

  # CSSファイルを抽出して生成するかどうか
  extract_css: false

  # 静的アセットの拡張子
  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  # 拡張子のリスト
  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

# 開発環境の設定
development:
  <<: *default
  compile: true

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

# テスト環境の設定
test:
  <<: *default
  compile: true
  public_output_path: packs-test

# 本番環境の設定
production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
